Replace Travis with GH Workflows
RockefellerArchiveCenter/digitized_av_trigger pull request #5
Opened 2024-11-12 21:19 UTC by HaSistrunk

Removes Travis and creates tests and deploy workflows for GitHub Actions. 
Also adds branch enforcement and cleans up README to remove Travis build status.

2024-11-13 15:16 UTC, helrond approved these changes

2024-11-13 20:50 UTC, ioduok approved these changes

2024-11-13 20:52 UTC, p-galligan approved these changes

2024-11-15 20:05 UTC, p-galligan requested changes

2024-11-15 20:05 UTC, p-galligan commented on .github/workflows/deploy.yml
> +      - development
We don't actually have a dev lambda S3 bucket, so I think we should remove this.

2024-11-15 20:05 UTC, p-galligan commented on .github/workflows/deploy.yml
> +          --function-name arn:aws:lambda:$AWS_REGION:$AWS_LAMBDA_ACCOUNT_ID:function:$LAMBDA_NAME
`$AWS_LAMBDA_ACCOUNT_ID` should be `$ {{ secrets.AWS_LAMBDA_ACCOUNT_ID }}

2024-11-15 20:15 UTC, p-galligan commented on .github/workflows/deploy.yml
> +        run: aws s3 cp $LAMBDA_NAME.zip s3://$LAMBDA_BUCKET_NAME/$LAMBDA_NAME.zip
`$LAMBDA_BUCKET_NAME` should be ${{ secrets.$LAMBDA_BUCKET_NAME }}

2024-11-15 20:32 UTC, p-galligan approved these changes

2024-11-18 14:10 UTC, p-galligan approved these changes

2024-11-18 15:56 UTC, merged